project_id = "pqfrgqadexairkmctbtj"

[functions.moolre-payment]
verify_jwt = false

[functions.moolre-sms]
verify_jwt = false

[functions.moolre-webhook]
verify_jwt = false

[functions.send-pending-sms]
verify_jwt = false

[functions.manage-roles]
verify_jwt = false
